In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv(r"C:\Users\DELL\OneDrive\Desktop\Heart-Disease\Heart-Disease-Prediction-Machine-Learning-Project-Using-Kaggle-Dataset\dataset\heart.csv")
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
print(x)

[[40 'M' 'ATA' ... 'N' 0.0 'Up']
 [49 'F' 'NAP' ... 'N' 1.0 'Flat']
 [37 'M' 'ATA' ... 'N' 0.0 'Up']
 ...
 [57 'M' 'ASY' ... 'Y' 1.2 'Flat']
 [57 'F' 'ATA' ... 'N' 0.0 'Flat']
 [38 'M' 'NAP' ... 'N' 0.0 'Up']]


In [7]:
pip install scikit-learn

   ---------------------------------------- 0.0/8.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.9 MB 3.4 MB/s eta 0:00:03
   ------- -------------------------------- 1.6/8.9 MB 3.2 MB/s eta 0:00:03
   --------- ------------------------------ 2.1/8.9 MB 2.9 MB/s eta 0:00:03
   ---------- ----------------------------- 2.4/8.9 MB 2.8 MB/s eta 0:00:03
   ------------ --------------------------- 2.9/8.9 MB 2.9 MB/s eta 0:00:03
   --------------- ------------------------ 3.4/8.9 MB 2.6 MB/s eta 0:00:03
   ------------------ --------------------- 4.2/8.9 MB 2.7 MB/s eta 0:00:02
   --------------------- ------------------ 4.7/8.9 MB 2.7 MB/s eta 0:00:02
   ----------------------- ---------------- 5.2/8.9 MB 2.8 MB/s eta 0:00:02
   --------------------------- ------------ 6.0/8.9 MB 2.8 MB/s eta 0:00:02
   ----------------------------- ---------- 6.6/8.9 MB 2.8 MB/s eta 0:00:01
   -----------------------

In [8]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
le2 = LabelEncoder()
le6 = LabelEncoder()
le8 = LabelEncoder()
le10 = LabelEncoder()
x[:,1]=le1.fit_transform(x[:,1])
x[:,2]=le2.fit_transform(x[:,2])
x[:,6]=le6.fit_transform(x[:,6])
x[:,8]=le8.fit_transform(x[:,8])
x[:,10]=le10.fit_transform(x[:,10])

In [9]:
print(x)

[[40 1 1 ... 0 0.0 2]
 [49 0 2 ... 0 1.0 1]
 [37 1 1 ... 0 0.0 2]
 ...
 [57 1 0 ... 1 1.2 1]
 [57 0 1 ... 0 0.0 1]
 [38 1 2 ... 0 0.0 2]]


In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [11]:
print(x_train)

[[70 1 0 ... 1 2.0 1]
 [46 1 0 ... 1 1.5 1]
 [65 0 2 ... 0 0.8 2]
 ...
 [57 0 0 ... 0 0.0 2]
 [64 1 0 ... 1 4.0 0]
 [47 1 2 ... 0 0.0 2]]


In [12]:
print(x_test)

[[55 1 0 ... 0 0.1 1]
 [66 1 0 ... 0 0.4 1]
 [51 1 0 ... 0 0.0 1]
 ...
 [52 1 0 ... 0 0.0 2]
 [37 1 1 ... 0 0.0 2]
 [53 1 2 ... 1 0.0 1]]
