In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv(r"C:\Users\DELL\OneDrive\Desktop\Heart-Disease\Heart-Disease-Prediction-Machine-Learning-Project-Using-Kaggle-Dataset\dataset\heart.csv")
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
print(x)

[[40 'M' 'ATA' ... 'N' 0.0 'Up']
 [49 'F' 'NAP' ... 'N' 1.0 'Flat']
 [37 'M' 'ATA' ... 'N' 0.0 'Up']
 ...
 [57 'M' 'ASY' ... 'Y' 1.2 'Flat']
 [57 'F' 'ATA' ... 'N' 0.0 'Flat']
 [38 'M' 'NAP' ... 'N' 0.0 'Up']]


In [3]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [4]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
le2 = LabelEncoder()
le6 = LabelEncoder()
le8 = LabelEncoder()
le10 = LabelEncoder()
x[:,1]=le1.fit_transform(x[:,1])
x[:,2]=le2.fit_transform(x[:,2])
x[:,6]=le6.fit_transform(x[:,6])
x[:,8]=le8.fit_transform(x[:,8])
x[:,10]=le10.fit_transform(x[:,10])

In [5]:
print(x)

[[40 1 1 ... 0 0.0 2]
 [49 0 2 ... 0 1.0 1]
 [37 1 1 ... 0 0.0 2]
 ...
 [57 1 0 ... 1 1.2 1]
 [57 0 1 ... 0 0.0 1]
 [38 1 2 ... 0 0.0 2]]


In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [7]:
print(x_train)

[[70 1 0 ... 1 2.0 1]
 [46 1 0 ... 1 1.5 1]
 [65 0 2 ... 0 0.8 2]
 ...
 [57 0 0 ... 0 0.0 2]
 [64 1 0 ... 1 4.0 0]
 [47 1 2 ... 0 0.0 2]]


In [8]:
print(x_test)

[[55 1 0 ... 0 0.1 1]
 [66 1 0 ... 0 0.4 1]
 [51 1 0 ... 0 0.0 1]
 ...
 [52 1 0 ... 0 0.0 2]
 [37 1 1 ... 0 0.0 2]
 [53 1 2 ... 1 0.0 1]]


In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [10]:
print(x_train)

[[ 1.75354017  0.51740017 -0.82686398 ...  1.19939076  1.0553738
  -0.59357258]
 [-0.81787111  0.51740017 -0.82686398 ...  1.19939076  0.57784676
  -0.59357258]
 [ 1.21782949 -1.93273999  1.27683849 ... -0.83375663 -0.0906911
   1.0443307 ]
 ...
 [ 0.3606924  -1.93273999 -0.82686398 ... -0.83375663 -0.85473437
   1.0443307 ]
 [ 1.11068735  0.51740017 -0.82686398 ...  1.19939076  2.96548197
  -2.23147586]
 [-0.71072897  0.51740017  1.27683849 ... -0.83375663 -0.85473437
   1.0443307 ]]
